###
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json


{
    "email" : "zafari@npco.net",
    "username" : "ali",
    "password" : "123456",
    "mobile" : "09125400848",
    "confirm_password" : "123456"

}

###
POST  http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "username" : "ali",
    "password" : "123456"

}